path_smoother_node:
  ros__parameters:
    desired_velocity: 0.5
    points_per_meter: 10.0
    waypoints: [0.0, 0.0, 2.0, 1.0, 4.0, -1.0, 6.0, 0.0, 8.0, 2.0]

path_tracker_node:
  ros__parameters:
    lookahead_distance: 0.5
    max_linear_velocity: 1.0
    goal_tolerance: 0.1
    yaw_error_threshold: 0.5
    prediction_horizon: 1.0
